# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-05 13:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='exams',
        ),
        migrations.DeleteModel(
            name='Exams',
        ),
    ]
