# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-11 14:37
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_auto_20170605_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='variables',
            field=jsonfield.fields.JSONField(default={}),
        ),
    ]
